version: "3.7"

services:
  client:
    image: node:16-alpine
    working_dir: /home/node/app
    env_file:
      - "./docker/base.env"
    volumes:
      - ~/.npmrc:/root/.npmrc:ro
      - ./client:/home/node/app
      - client_container_node_modules:/home/node/app/node_modules
    ports:
      - "8080:8080"
    command: /bin/sh -c "apk add --no-cache --virtual .gyp python3 make g++ && npm install && npm run dev"

volumes:
    client_container_node_modules:
